# Generated by Django 6.0.4 on 2026-05-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propertylocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyLocation',
            new_name='PropertySlider',
        ),
    ]
