# Generated by Django 6.0.4 on 2026-05-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpcommission',
            name='source_type',
            field=models.CharField(default='utility', max_length=50),
        ),
        migrations.AlterField(
            model_name='erpcommission',
            name='wallet_hit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpcompanyasset',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpdividend',
            name='wallet_credited',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpdocument',
            name='e_sign',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpdocument',
            name='is_signed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpinstallmentplan',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpinstallmentplan',
            name='sms_sent_48h_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpinstallmentplan',
            name='sms_sent_due_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erplandrecord',
            name='namjari_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpmoneyreceipt',
            name='cheque_cleared',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpmoneyreceipt',
            name='cheque_notification_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpmoneyreceipt',
            name='created_by_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpmoneyreceipt',
            name='e_sign',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpoffer',
            name='sms_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='interested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='notification_sent_24h',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='notification_sent_2h',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpuser',
            name='is_investor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpuser',
            name='is_marketing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpvoucher',
            name='e_sign',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpwallettransaction',
            name='is_holiday',
            field=models.BooleanField(default=True),
        ),
    ]
