# Generated by Django 6.0.4 on 2026-05-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpbooking',
            name='gift_amount',
        ),
        migrations.RemoveField(
            model_name='erpbooking',
            name='gift_note',
        ),
    ]
