# Generated by Django 6.0.4 on 2026-05-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_erpinvestor_marketing_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpuser',
            name='role',
        ),
        migrations.AddField(
            model_name='erpuser',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
