# Generated by Django 6.0.4 on 2026-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_erpcommission_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpplot',
            name='balcony',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='bathroom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='bedroom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='building_orientation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='building_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='drawing_dining_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='electricity_backup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='garden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='hall',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='kitchen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='lift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='parking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='road',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='total_share',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='unit_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='unit_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='unit_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='unit_per_floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
