# Generated by Django 6.0.4 on 2026-05-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_erpbooking_gift_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erpinstallmentplan',
            old_name='sms_sent_48h',
            new_name='sms_sent_48h_flag',
        ),
        migrations.RenameField(
            model_name='erpinstallmentplan',
            old_name='sms_sent_due',
            new_name='sms_sent_due_flag',
        ),
        migrations.RemoveField(
            model_name='erpinstallmentplan',
            name='paid_date',
        ),
    ]
