# Generated by Django 6.0.4 on 2026-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_erpplot_balcony_erpplot_bathroom_erpplot_bedroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpuser',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='erpuser',
            name='is_investor',
        ),
        migrations.RemoveField(
            model_name='erpuser',
            name='is_marketing',
        ),
        migrations.AlterField(
            model_name='erpuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='erp/users/'),
        ),
    ]
