# Generated by Django 6.0.4 on 2026-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_erpuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['username'], name='mainapp_erp_usernam_9e35ad_idx'),
        ),
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['email'], name='mainapp_erp_email_c889b3_idx'),
        ),
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['employee_id'], name='mainapp_erp_employe_487cbb_idx'),
        ),
    ]
