# Generated by Django 6.0.4 on 2026-05-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_erpuser_mainapp_erp_usernam_9e35ad_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpuser',
            name='roles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
