# Generated by Django 6.0.4 on 2026-05-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_erpuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpinvestment',
            name='amount_returned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='audit_trail',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='dividend_payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='investments/docs/'),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='duration',
            field=models.CharField(default='12 Months', max_length=50),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='full_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='investment_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='partial_return_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='partial_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erpinvestor',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='erpinvestor',
            name='bank_account_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='erpinvestor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpinvestor',
            name='nid_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpinvestor',
            name='nominee_details',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpinvestor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='erpplot',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LandPowerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_power_assigned', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conversion_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_land_assigned', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transfer_status', models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('cancellation_status', models.CharField(blank=True, choices=[('cancel', 'Cancel'), ('retain', 'Retain')], max_length=10)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('reason_for_cancellation', models.TextField(blank=True, null=True)),
                ('power_return_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_power', to='mainapp.erpinvestment')),
            ],
        ),
    ]
