# Generated by Django 6.0.4 on 2026-05-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_erpinvestment_amount_returned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPLandOwner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('nid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('power_of_attorney_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('power_of_attorney_doc', models.FileField(blank=True, null=True, upload_to='erp/land/attorney/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERPSupplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=150, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('contract_details', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ERPLandAcquisition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acquisition_code', models.CharField(max_length=50, unique=True)),
                ('khatiyan_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('total_area', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('price_per_decimal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('area_purchased', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('land_status', models.CharField(choices=[('power_of_attorney', 'Power of Attorney'), ('saf_kabala', 'Saf-Kabala')], default='power_of_attorney', max_length=30)),
                ('is_mutated', models.BooleanField(default=False)),
                ('is_surveyed', models.BooleanField(default=False)),
                ('related_documents', models.FileField(blank=True, null=True, upload_to='erp/land/documents/')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_acquisitions', to='mainapp.erplandowner')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_acquisitions', to='mainapp.erpsupplier')),
            ],
        ),
    ]
