# Generated by Django 6.0.4 on 2026-05-13 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_erplandowner_erpsupplier_erplandacquisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpoffer',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='erpvoucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to='mainapp.erpuser'),
        ),
        migrations.AlterField(
            model_name='erpvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to='mainapp.erpuser'),
        ),
        migrations.AlterField(
            model_name='erpvoucher',
            name='credit_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_vouchers', to='mainapp.erpaccounthead'),
        ),
        migrations.AlterField(
            model_name='erpvoucher',
            name='debit_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_vouchers', to='mainapp.erpaccounthead'),
        ),
        migrations.AlterField(
            model_name='erpvoucher',
            name='e_sign',
            field=models.BooleanField(default=False),
        ),
    ]
