# Generated by Django 6.0.4 on 2026-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_erpoffer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpwallet',
            name='wallet_type',
            field=models.CharField(choices=[('marketing', 'Marketing Officer Wallet'), ('investor', 'Investor Wallet'), ('customer', 'Customer Wallet'), ('customer_care', 'Customer Care Wallet'), ('employee', 'Employee Wallet'), ('accounts', 'Accounts Officer Wallet'), ('admin', 'Admin Wallet'), ('general', 'General Wallet')], default='general', max_length=20),
        ),
    ]
