# Generated by Django 6.0.4 on 2026-05-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_erpwallet_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erploan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to='mainapp.erpuser'),
        ),
        migrations.AlterField(
            model_name='erploan',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='erploan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='mainapp.erpuser'),
        ),
    ]
