# Generated by Django 6.0.4 on 2026-05-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_erploan_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_visits', to='mainapp.erpuser'),
        ),
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='interested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='notification_sent_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='notification_sent_2h',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='mainapp.erpproject'),
        ),
    ]
