# Generated by Django 6.0.4 on 2026-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_erpuser_password_hash_erpuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='is_marketingOfficer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='erpproject',
            name='project_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('flat', 'Flat'), ('investment', 'Investment'), ('commercial', 'Commercial'), ('mixed', 'Mixed')], default='lot', max_length=20),
        ),
    ]
