# Generated by Django 6.0.4 on 2026-05-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_erpuser_is_employee_erpuser_is_marketingofficer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpuser',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='erpuser',
            name='is_marketingOfficer',
        ),
    ]
