# Generated by Django 6.0.4 on 2026-05-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_erpuser_is_employee_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='erpuser',
            name='mainapp_erp_employe_487cbb_idx',
        ),
        migrations.RemoveField(
            model_name='erpuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='erpuser',
            name='employee_id',
        ),
    ]
