# Generated by Django 6.0.4 on 2026-05-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_erpuser_mainapp_erp_employe_487cbb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='referd_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
