# Generated by Django 6.0.4 on 2026-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_erpuser_referd_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpcustomer',
            name='referd_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
