# Generated by Django 6.0.4 on 2026-05-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_erpcustomer_referd_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erpuser',
            old_name='referd_by',
            new_name='referred_by',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='referd_by',
        ),
    ]
