# Generated by Django 6.0.4 on 2026-05-19 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_rename_referd_by_erpuser_referred_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpcustomer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
