# Generated by Django 6.0.4 on 2026-05-20 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_erpcustomer_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('booking', 'Booking'), ('down_payment', 'Down-payment'), ('installment', 'Installment'), ('token_money', 'Token-Money'), ('advance', 'Advance'), ('loan', 'Loan'), ('transferred', 'Transferred')], default='booking', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='mainapp.erpcustomer')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_transactions', to='mainapp.erpplot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='mainapp.erpproject')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_transactions', to=settings.AUTH_USER_MODEL)),
                ('transferred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='mainapp.erpcustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
