# Generated by Django 6.0.4 on 2026-05-20 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpplot',
            name='plot_type',
            field=models.CharField(choices=[('Plot', 'Plot'), ('flat', 'Flat')], default='residential', max_length=20),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(default=0)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_type', models.CharField(default='sale', max_length=30)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mainapp.erpplot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mainapp.erpproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
