# Generated by Django 6.0.4 on 2026-05-20 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_erpplot_plot_type_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('plot', 'Plot'), ('flat', 'Flat'), ('both', 'Both')], default='lot', max_length=20)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('upazila', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mouza', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('total_land_area', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('land_unit', models.CharField(default='katha', max_length=20)),
                ('total_plots', models.IntegerField(default=0)),
                ('available_plots', models.IntegerField(default=0)),
                ('total_project_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('sold_out', 'Sold Out'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='erp/projects/')),
                ('layout_image', models.ImageField(blank=True, default='', null=True, upload_to='erp/projects/layouts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='erpplot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='erpplot',
            name='project',
        ),
        migrations.AlterField(
            model_name='commission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erpbooking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erpcommissionrule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erpdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erpinvestment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erpinvestment',
            name='transferred_to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_investments', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erplandrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erplead',
            name='interested_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erpoffer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='mainapp.project'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plot_number', models.CharField(max_length=50)),
                ('plot_type', models.CharField(choices=[('plot', 'Plot'), ('flat', 'Flat')], default='plot', max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sector', models.DecimalField(decimal_places=2, max_digits=10)),
                ('block', models.DecimalField(decimal_places=2, max_digits=10)),
                ('road', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_number', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('area_unit', models.CharField(default='katha', max_length=20)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('facing', models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], default='', max_length=20, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('flat_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('sold', 'Sold'), ('hold', 'On Hold'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('layout_x', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('layout_y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/images/')),
                ('total_share', models.CharField(blank=True, max_length=255, null=True)),
                ('building_type', models.CharField(blank=True, max_length=255, null=True)),
                ('building_orientation', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_per_floor', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_a', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_b', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_c', models.CharField(blank=True, max_length=255, null=True)),
                ('bedroom', models.CharField(blank=True, max_length=255, null=True)),
                ('bathroom', models.CharField(blank=True, max_length=255, null=True)),
                ('balcony', models.CharField(blank=True, max_length=255, null=True)),
                ('drawing_dining_room', models.CharField(blank=True, max_length=255, null=True)),
                ('kitchen', models.CharField(blank=True, max_length=255, null=True)),
                ('garden', models.CharField(blank=True, max_length=255, null=True)),
                ('lift', models.CharField(blank=True, max_length=255, null=True)),
                ('parking', models.CharField(blank=True, max_length=255, null=True)),
                ('hall', models.CharField(blank=True, max_length=255, null=True)),
                ('electricity_backup', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='mainapp.project')),
            ],
            options={
                'ordering': ['plot_number'],
                'unique_together': {('project', 'plot_number')},
            },
        ),
        migrations.AlterField(
            model_name='commission',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mainapp.property'),
        ),
        migrations.AlterField(
            model_name='erpbooking',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mainapp.property'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_transactions', to='mainapp.property'),
        ),
        migrations.DeleteModel(
            name='ERPProject',
        ),
        migrations.DeleteModel(
            name='ERPPlot',
        ),
    ]
