# Generated by Django 6.0.4 on 2026-05-22 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0025_erppermission_erprolepermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erpuser",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
