# Generated by Django 6.0.4 on 2026-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_erpuser_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpcustomer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='referred_by',
        ),
        migrations.AlterField(
            model_name='erpcustomer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='erpcustomer',
            name='nid_image',
            field=models.ImageField(blank=True, null=True, upload_to='erp/customers/nid/'),
        ),
    ]
