# Generated by Django 6.0.4 on 2026-05-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_remove_erpcustomer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpcustomer',
            options={},
        ),
    ]
