# Generated by Django 6.0.4 on 2026-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_erpcustomer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpemployee',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='erpemployee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='erpemployee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='erpemployee',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='erpemployee',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='erpemployee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='erpemployee',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='erpemployee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
