# Generated by Django 6.0.4 on 2026-06-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_erpemployee_options_remove_erpemployee_address_and_more'),
    ]

    operations = [
        # ✅ RemoveField সরানো হয়েছে — field আগেই নেই
        migrations.AlterUniqueTogether(
            name='erprolepermission',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ERPPermission',
        ),
        migrations.DeleteModel(
            name='ERPRolePermission',
        ),
    ]