# Generated by Django 6.0.4 on 2026-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_remove_erprolepermission_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erpuser',
            old_name='address',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='nid_image',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='phone_alt',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='erpcustomer',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='erpuser',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='nid_image',
            field=models.ImageField(blank=True, null=True, upload_to='erp/customers/nid/'),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='permanent_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='phone_alt',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='present_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='erpuser',
            name='spouse_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
