# Generated by Django 6.0.4 on 2026-06-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_rename_address_erpuser_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpcustomer',
            options={'ordering': ['-created_at']},
        ),
    ]
