# Generated by Django 6.0.4 on 2026-06-01 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_erpcustomer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpcustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
