# Generated by Django 6.0.4 on 2026-06-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_alter_erpcustomer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mainapp.erpbooking'),
        ),
        migrations.AlterField(
            model_name='erpbooking',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
