# Generated by Django 6.0.4 on 2026-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('booking_money', 'Booking-Money'), ('down_payment', 'Down-payment'), ('installment', 'Installment'), ('token_money', 'Token-Money'), ('advance', 'Advance'), ('loan', 'Loan'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('registration', 'Registration'), ('land_development', 'Land-Development'), ('parking', 'Parking'), ('utility', 'Utility'), ('others', 'Others')], default='booking', max_length=20),
        ),
    ]
