# Generated by Django 6.0.4 on 2026-06-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('booking_money', 'Booking-Money'), ('down_payment', 'Down-payment'), ('installment', 'Installment'), ('token_money', 'Token-Money'), ('advance', 'Advance'), ('loan', 'Loan'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('registration', 'Registration'), ('land_development', 'Land-Development'), ('parking', 'Parking'), ('utility', 'Utility'), ('others', 'Others')], default='booking_money', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
