# Generated by Django 6.0.4 on 2026-06-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_alter_transaction_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpemployee',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='erpemployee',
            name='department',
            field=models.CharField(blank=True, choices=[('management', 'Management'), ('accounts', 'Accounts'), ('marketing', 'Marketing'), ('customer_care', 'Customer Care'), ('hr', 'Human Resources'), ('legal', 'Legal')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='erpemployee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
