# Generated by Django 6.0.4 on 2026-06-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_remove_erpemployee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpemployee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='erpemployee',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='erpemployee',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ERPAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('holiday_days', models.IntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='mainapp.erpemployee')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
