# Generated by Django 6.0.4 on 2026-06-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_erpemployee_is_active_alter_erpemployee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(choices=[('govt', 'Government Holiday'), ('office', 'Office Holiday'), ('other', 'Other')], default='govt', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
