# Generated by Django 6.0.4 on 2026-06-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_erpholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='absent', max_length=20),
        ),
    ]
