# Generated by Django 6.0.4 on 2026-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_alter_erpattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpinvestor',
            name='investor_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
