# Generated by Django 6.0.4 on 2026-06-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_alter_erpinvestor_investor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erpmarketingofficer',
            old_name='commission_rate_lot',
            new_name='commission_rate_plot',
        ),
        migrations.RemoveField(
            model_name='erpmarketingofficer',
            name='upline',
        ),
    ]
