# Generated by Django 6.0.4 on 2026-06-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_rename_commission_rate_lot_erpmarketingofficer_commission_rate_plot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpprojectvisit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='mainapp.project'),
        ),
    ]
