# Generated by Django 6.0.4 on 2026-06-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_alter_erpprojectvisit_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erploan',
            name='user',
        ),
        migrations.AddField(
            model_name='erploan',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='mainapp.erpemployee'),
        ),
    ]
