# Generated by Django 6.0.4 on 2026-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_remove_erploan_user_erploan_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpinstallmentplan',
            name='sms_sent_48h_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='erpinstallmentplan',
            name='sms_sent_due_flag',
            field=models.BooleanField(default=False),
        ),
    ]
