# Generated by Django 6.0.4 on 2026-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_alter_erpinstallmentplan_sms_sent_48h_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpmarketingofficer',
            name='officer_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
