# Generated by Django 6.0.4 on 2026-06-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_alter_erpmarketingofficer_officer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Booking Payment',
                'verbose_name_plural': 'Booking Payments',
            },
        ),
        migrations.CreateModel(
            name='DownPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Down Payment',
                'verbose_name_plural': 'Down Payments',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Installment Payment',
                'verbose_name_plural': 'Installment Payments',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Investment Payment',
                'verbose_name_plural': 'Investment Payments',
            },
        ),
        migrations.CreateModel(
            name='LandDevPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Land Development Payment',
                'verbose_name_plural': 'Land Development Payments',
            },
        ),
        migrations.CreateModel(
            name='ParkingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Parking Payment',
                'verbose_name_plural': 'Parking Payments',
            },
        ),
        migrations.CreateModel(
            name='RegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Registration Payment',
                'verbose_name_plural': 'Registration Payments',
            },
        ),
        migrations.CreateModel(
            name='TransferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Transfer Payment',
                'verbose_name_plural': 'Transfer Payments',
            },
        ),
        migrations.CreateModel(
            name='UtilityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Utility Payment',
                'verbose_name_plural': 'Utility Payments',
            },
        ),
    ]
