# Generated by Django 6.0.4 on 2026-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_bookingpayment_downpayment_installmentpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('booking', 'Booking Money'), ('installment', 'Installment'), ('down_payment', 'Down Payment'), ('investment', 'Investment'), ('registration', 'Registration'), ('land_dev', 'Land Development'), ('parking', 'Parking'), ('transfer', 'Transfer'), ('utility', 'Utility')], max_length=20)),
                ('gen_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_6', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gen_7', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Percentage',
                'verbose_name_plural': 'Percentages',
            },
        ),
        migrations.DeleteModel(
            name='BookingPayment',
        ),
        migrations.DeleteModel(
            name='DownPayment',
        ),
        migrations.DeleteModel(
            name='InstallmentPayment',
        ),
        migrations.DeleteModel(
            name='InvestmentPayment',
        ),
        migrations.DeleteModel(
            name='LandDevPayment',
        ),
        migrations.DeleteModel(
            name='ParkingPayment',
        ),
        migrations.DeleteModel(
            name='RegistrationPayment',
        ),
        migrations.DeleteModel(
            name='TransferPayment',
        ),
        migrations.DeleteModel(
            name='UtilityPayment',
        ),
    ]
