# Generated by Django 6.0.4 on 2026-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_percentage_delete_bookingpayment_delete_downpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpholiday',
            name='holiday_type',
            field=models.CharField(choices=[('govt', 'Government Holiday'), ('company_holiday', 'Company Holiday'), ('weekend', 'Weekend'), ('others', 'Others')], default='govt', max_length=50),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='gen_0',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='gen_1',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='gen_2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='gen_3',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='gen_4',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='gen_5',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='gen_6',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='gen_7',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
