# Generated by Django 6.0.4 on 2026-06-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_alter_erpholiday_holiday_type_alter_percentage_gen_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpmoneyreceipt',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_receipts', to='mainapp.erpbooking'),
        ),
        migrations.AlterField(
            model_name='erpmoneyreceipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_receipts', to='mainapp.erpcustomer'),
        ),
    ]
