# Generated by Django 6.0.4 on 2026-06-08 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_alter_erpmoneyreceipt_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmoneyreceipt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='erpmoneyreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
