# Generated by Django 6.0.4 on 2026-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_erpmoneyreceipt_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpbooking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
