# Generated by Django 6.0.4 on 2026-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_alter_erpbooking_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpsupplier',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
