# Generated by Django 6.0.4 on 2026-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_alter_erpsupplier_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='erplandowner',
            name='owner_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
