# Generated by Django 6.0.4 on 2026-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_erplandowner_owner_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erpdividend',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='erpdividend',
            name='dividend_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='erpinvestment',
            name='yearly_dividend_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='erpdividend',
            unique_together={('investment', 'month', 'year', 'dividend_type')},
        ),
    ]
