# Generated by Django 6.0.4 on 2026-06-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_alter_erpdividend_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erpdividend',
            unique_together={('investment', 'year', 'dividend_type')},
        ),
    ]
