# Generated by Django 6.0.4 on 2026-06-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_alter_erpdividend_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpdividend',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='erpdividend',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
