# Generated by Django 6.0.4 on 2026-06-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_alter_erpdividend_month_alter_erpdividend_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpdividend',
            options={'ordering': ['-id']},
        ),
    ]
