# Generated by Django 6.0.4 on 2026-06-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_alter_erpdividend_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpwallettransaction',
            name='transaction_direction',
            field=models.CharField(choices=[('in', 'Inflow'), ('out', 'Outflow')], default='in', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_direction',
            field=models.CharField(choices=[('in', 'Inflow'), ('out', 'Outflow')], default='in', max_length=10),
        ),
    ]
