# Generated by Django 6.0.4 on 2026-06-16 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_erpwallettransaction_transaction_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_transactions', to='mainapp.property'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='mainapp.project'),
        ),
    ]
