# Generated by Django 6.0.4 on 2026-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0063_alter_transaction_plot_alter_transaction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpvoucher',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erpvoucher',
            name='cheque_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erpvoucher',
            name='cheque_cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erpvoucher',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erpvoucher',
            name='cheque_deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erpvoucher',
            name='cheque_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erpvoucher',
            name='cheque_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='erpvoucher',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_banking', 'Mobile Banking (bKash/Nagad)'), ('online', 'Online Transfer')], default='cash', max_length=30),
        ),
    ]
