# Generated by Django 6.0.4 on 2026-05-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERPPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(choices=[('project', 'Project'), ('plot', 'Plot'), ('booking', 'Booking'), ('installment', 'Installment'), ('receipt', 'Money Receipt'), ('commission', 'Commission'), ('wallet', 'Wallet'), ('lead', 'Lead'), ('attendance', 'Attendance'), ('payroll', 'Payroll'), ('investment', 'Investment'), ('dividend', 'Dividend'), ('officer_request', 'Officer Request'), ('document', 'Document'), ('offer', 'Offer')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module', 'action'],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ERPRolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('marketing_officer', 'Marketing Officer'), ('marketing_manager', 'Marketing Manager'), ('customer', 'Customer'), ('investor', 'Investor')], max_length=50)),
                ('scope', models.CharField(choices=[('own', 'Own Data Only'), ('all', 'All Data')], default='own', help_text='own = শুধু নিজের data, all = সব data', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accesscontrol.erppermission')),
            ],
            options={
                'ordering': ['role', 'permission__module'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
