# Generated by Django 6.0.4 on 2026-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erppermission',
            name='module',
            field=models.CharField(choices=[('project', 'Project'), ('property', 'Property'), ('booking', 'Booking'), ('installment', 'Installment'), ('receipt', 'Money Receipt'), ('commission', 'Commission'), ('wallet', 'Wallet'), ('lead', 'Lead'), ('attendance', 'Attendance'), ('payroll', 'Payroll'), ('investment', 'Investment'), ('dividend', 'Dividend'), ('officer_request', 'Officer Request'), ('document', 'Document'), ('offer', 'Offer')], max_length=50),
        ),
    ]
