# Generated by Django 6.0.4 on 2026-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0002_alter_erppermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erppermission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('cancel', 'Cancel'), ('transfer', 'Transfer'), ('export', 'Export'), ('download', 'Download')], max_length=20),
        ),
        migrations.AlterField(
            model_name='erppermission',
            name='module',
            field=models.CharField(choices=[('user', 'User Management'), ('project', 'Project'), ('property', 'Property'), ('booking', 'Booking'), ('installment', 'Installment'), ('receipt', 'Money Receipt'), ('commission', 'Commission'), ('wallet', 'Wallet'), ('lead', 'Lead'), ('attendance', 'Attendance'), ('payroll', 'Payroll'), ('investment', 'Investment'), ('dividend', 'Dividend'), ('officer_request', 'Officer Request'), ('document', 'Document'), ('offer', 'Offer'), ('project_visit', 'Project Visit'), ('land_record', 'Land Record'), ('customer', 'Customer'), ('employee', 'Employee'), ('loan', 'Loan'), ('voucher', 'Voucher'), ('asset', 'Company Asset'), ('sms', 'SMS Log'), ('report', 'Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='erprolepermission',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accounts', 'Accounts Officer'), ('hr', 'HR Manager'), ('customer_care', 'Customer Care'), ('employee', 'Employee'), ('marketing_officer', 'Marketing Officer'), ('marketing_manager', 'Marketing Manager'), ('customer', 'Customer'), ('investor', 'Investor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='erprolepermission',
            name='scope',
            field=models.CharField(choices=[('own', 'Own Data Only'), ('team', 'Team Data'), ('all', 'All Data')], default='own', max_length=10),
        ),
    ]
